CREATE SCHEMA IF NOT EXISTS SABORESDECASA;

CREATE TABLE SABORESDECASA.FORMATO(
ID SERIAL NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(180)
);

CREATE TABLE SABORESDECASA.PLATO (
    ID SERIAL  NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    PRECIO NUMERIC(10,2) NOT NULL,
    FORMATO SMALLINT NOT NULL
);

CREATE TABLE SABORESDECASA.LIN_PEDIDO(
    ID SERIAL  NOT NULL PRIMARY KEY,
    PLATO SMALLINT NOT NULL,
    CANTIDAD SMALLINT NOT NULL,
    VALOR NUMERIC(10,2) NOT NULL,
    PEDIDO SMALLINT NOT NULL
);

CREATE TABLE SABORESDECASA.PEDIDO(
    ID SERIAL  NOT NULL PRIMARY KEY,
    FECHA DATE NOT NULL,
    TOTAL NUMERIC(10,2),
    CLIENTE SMALLINT
);

CREATE TABLE SABORESDECASA.CLIENTE(
ID SERIAL NOT NULL PRIMARY KEY, 
NOMBRE VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR (150) NOT NULL,
DNI VARCHAR(20) NOT NULL,
TELEFONO VARCHAR(18) NOT NULL
);

ALTER TABLE SABORESDECASA.LIN_PEDIDO ADD CONSTRAINT FK_PLATO_LIN_PEDIDO FOREIGN KEY (PLATO) REFERENCES SABORESDECASA.PLATO (ID);

ALTER TABLE SABORESDECASA.PLATO ADD CONSTRAINT FK_PLATO_FORMATO FOREIGN KEY (FORMATO) REFERENCES SABORESDECASA.FORMATO(ID);

ALTER TABLE SABORESDECASA.LIN_PEDIDO ADD CONSTRAINT FK_LIN_PEDIDO_PEDIDO FOREIGN KEY (PEDIDO) REFERENCES SABORESDECASA.PEDIDO (ID);

ALTER TABLE SABORESDECASA.PEDIDO ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES SABORESDECASA.CLIENTE (ID);

INSERT INTO SABORESDECASA.FORMATO(NOMBRE) VALUES ('RACION');

INSERT INTO SABORESDECASA.FORMATO(NOMBRE) VALUES ('MEDIA_RACION');

INSERT INTO SABORESDECASA.FORMATO(NOMBRE) VALUES ('TAPA');

INSERT INTO SABORESDECASA.PLATO (NOMBRE,PRECIO,FORMATO) VALUES ('PAPAS CON CHOCO',5.20,1);

INSERT INTO SABORESDECASA.PLATO (NOMBRE, PRECIO, FORMATO) VALUES ('ENSALADA CESAR', 4.50,3);

INSERT INTO SABORESDECASA.PLATO (NOMBRE,PRECIO,FORMATO) VALUES ('PAPAS CON CHOCO',3.15,3);

INSERT INTO SABORESDECASA.PLATO (NOMBRE,PRECIO,FORMATO) VALUES ('PAPAS CON CHOCO',5.20,2);

INSERT INTO SABORESDECASA.PLATO (NOMBRE, PRECIO, FORMATO) VALUES ('ENSALADA CESAR', 4.50, 1);

INSERT INTO SABORESDECASA.PLATO (NOMBRE, PRECIO, FORMATO) VALUES ('PIZZA MARGHERITA', 8.00, 2);

INSERT INTO SABORESDECASA.PLATO (NOMBRE, PRECIO, FORMATO) VALUES ('TACOS AL PASTOR', 7.25, 2);

INSERT INTO SABORESDECASA.PLATO (NOMBRE, PRECIO, FORMATO) VALUES ('HAMBURGUESA CLÁSICA', 9.50, 3);

INSERT INTO SABORESDECASA.PLATO (NOMBRE, PRECIO, FORMATO) VALUES ('SOPA DE LENTEJAS', 5.00, 2);

INSERT INTO SABORESDECASA.CLIENTE (NOMBRE, APELLIDOS, DNI, TELEFONO) VALUES ('Juan', 'Pérez', '12345678A', '600123456');

INSERT INTO SABORESDECASA.CLIENTE (NOMBRE, APELLIDOS, DNI, TELEFONO) VALUES ('María', 'García', '23456789B', '601234567');

INSERT INTO SABORESDECASA.CLIENTE (NOMBRE, APELLIDOS, DNI, TELEFONO) VALUES ('Luis', 'Martínez', '34567890C', '602345678');

INSERT INTO SABORESDECASA.CLIENTE (NOMBRE, APELLIDOS, DNI, TELEFONO) VALUES ('Ana', 'Sánchez', '45678901D', '603456789');

INSERT INTO SABORESDECASA.CLIENTE (NOMBRE, APELLIDOS, DNI, TELEFONO) VALUES ('Carlos', 'Lopez', '56789012E', '604567890');

INSERT INTO SABORESDECASA.PEDIDO (FECHA, TOTAL, CLIENTE) VALUES (CURRENT_DATE, 22.40, 1);

INSERT INTO SABORESDECASA.LIN_PEDIDO (PLATO, CANTIDAD, VALOR, PEDIDO) VALUES 
(1, 2, 14.40, 1),  
(3, 1, 8.00, 1); 


INSERT INTO SABORESDECASA.PEDIDO (FECHA, TOTAL, CLIENTE) VALUES (CURRENT_DATE, 15.75, 2);
INSERT INTO SABORESDECASA.LIN_PEDIDO (PLATO, CANTIDAD, VALOR, PEDIDO) VALUES 
(2, 1, 4.50, 2),  
(4, 1, 5.20, 2),  
(6, 1, 6.05, 2);


INSERT INTO SABORESDECASA.PEDIDO (FECHA, TOTAL, CLIENTE) VALUES (CURRENT_DATE, 20.25, 3);
INSERT INTO SABORESDECASA.LIN_PEDIDO (PLATO, CANTIDAD, VALOR, PEDIDO) VALUES 
(5, 2, 10.00, 3),  
(8, 1, 9.50, 3),  
(1, 1, 3.15, 3);


SELECT * FROM SABORESDECASA.lin_pedido p  WHERE p.pedido = 1; 



SELECT * FROM SABORESDECASA.PLATO  p JOIN SABORESDECASA.FORMATO f ON p.FORMATO = F.ID WHERE f.NOMBRE= 'TAPA';

