CREATE SCHEMA IF NOT EXISTS SABORESDECASA;

CREATE TYPE SABORESDECASA.FORMATO AS ENUM ('TAPA','MEDIA_RACION','RACION');

CREATE TABLE SABORESDECASA.PLATO (
    ID SERIAL  NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100),
    PRECIO_BASE NUMERIC(10,2),
    FORMATO SABORESDECASA.FORMATO
);

CREATE TABLE SABORESDECASA.LIN_PEDIDO(
    ID SERIAL  NOT NULL PRIMARY KEY,
    ID_PLATO SMALLINT NOT NULL,
    CANTIDAD SMALLINT NOT NULL,
    VALOR NUMERIC(10,2) NOT NULL,
    ID_PEDIDO SMALLINT NOT NULL
);

CREATE TABLE SABORESDECASA.PEDIDO(
    ID SERIAL  NOT NULL PRIMARY KEY,
    ID_PEDIDO SMALLINT NOT NULL,
    FECHA DATE NOT NULL,
    VALOR NUMERIC(10,2) NOT NULL,
    ID_CLIENTE SMALLINT
);

CREATE TABLE SABORESDECASA.CLIENTE(
ID SERIAL NOT NULL PRIMARY KEY, 
NOMBRE VARCHAR(250) NOT NULL,
APELLIDOS VARCHAR (250) NOT NULL,
DNI VARCHAR(20) NOT NULL,
TELEFONO VARCHAR(15) NOT NULL
);

ALTER TABLE SABORESDECASA.LIN_PEDIDO ADD CONSTRAINT FK_PLATO_LIN_PEDIDO FOREIGN KEY (ID_PLATO) REFERENCES SABORESDECASA.PLATO (ID);

ALTER TABLE SABORESDECASA.LIN_PEDIDO ADD CONSTRAINT FK_LIN_PEDIDO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES SABORESDECASA.PEDIDO (ID);

ALTER TABLE SABORESDECASA.PEDIDO ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES SABORESDECASA.CLIENTE (ID);